#LINUX AMD64 && ARM64
# Oracle Images: https://github.com/graalvm/container/tree/master/graalvm-community
FROM debian:stable-slim AS graalvm_setup
ENV GRAALVM_HOME="/usr/local/graalvm"
ENV JAVA_VERSION="21"

# Releases: https://github.com/graalvm/graalvm-ce-builds/releases/
ENV AMD64="https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-x64_bin.tar.gz"
ENV ARM64="https://github.com/graalvm/graalvm-ce-builds/releases/download/jdk-21.0.2/graalvm-community-jdk-21.0.2_linux-aarch64_bin.tar.gz"

# Prerequisites: https://www.graalvm.org/latest/reference-manual/native-image/#prerequisites
# locales && locales-all: https://github.com/oracle/graal/issues/8792#issuecomment-2189166038 (java commands such as Path.resolve() fail without it when locating special chars in the path)
RUN set -eux; \
    GRAALVM_DOWNLOAD_URL=$(if [ "$(uname -m)" = "aarch64" ]; then echo "${ARM64}"; else echo "${AMD64}"; fi) \
	&& mkdir -p "${GRAALVM_HOME}" \
    && apt-get -y update \
    && apt-get -y install curl \
    && apt-get -y install locales locales-all \
    && apt-get -y install --no-install-recommends build-essential libz-dev zlib1g-dev \
    && curl -sSL -o graalvm.tar.gz ${GRAALVM_DOWNLOAD_URL} \
    && tar -zxf graalvm.tar.gz -C "${GRAALVM_HOME}" --strip-components 1 \
    && rm -f graalvm.tar.gz \
	&& apt-get -y clean \
	&& rm -rf /var/lib/apt/lists/*

# COPY THE SOURCES
FROM graalvm_setup AS copy_sources
COPY src ./src
COPY .mvn ./.mvn
COPY mvnw pom.xml ./

# BUILD THE NATIVE IMAGE
# [SYSTEM] docker build -t app-native -f Dockerfile .
# [ARCH] docker buildx build --platform linux/amd64 -t app-native -f Dockerfile --load .
FROM copy_sources AS native_build

ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8

RUN (chmod +x mvnw && JAVA_HOME="${GRAALVM_HOME}" ./mvnw clean package -B -q -DskipTests -Pnative)

# USED TO EXPORT THE NATIVE IMAGE
# [SYSTEM] docker build -t app-native -f Dockerfile . && docker build --target export . --output target
# [ARCH] docker buildx build --platform linux/amd64 --output type=docker -t app-native -f Dockerfile . && docker buildx build --platform linux/arm64 --target export .  --output target
FROM scratch AS export
COPY --from=native_build ./target/*.native ./app.native

# RUN THE NATIVE IMAGE
# [SYSTEM] docker build -t app-native -f Dockerfile . && docker run --rm -p 8080:8080 app-native
# [ARCH] docker buildx build --platform linux/amd64 -t app-native -f Dockerfile --load . && docker run --rm -p 8080:8080 app-native
FROM debian:stable-slim AS native_image
COPY --from=native_build ./target/*.native ./app.native

ENV PLAYWRIGHT_BROWSERS_PATH=/ms-playwright
ENV PLAYWRIGHT_CLI_DIR=/opt/playwright-cli/driver

########## SETUP PLAYWRIGHT DEPENDENCIES START ##########
RUN apt-get update && apt-get install -y --no-install-recommends \
      ca-certificates \
      curl \
      unzip \
    && rm -rf /var/lib/apt/lists/* \
    && PLAYWRIGHT_VERSION=$(/app.native --playwright-version | awk '{print $3}') \
    && curl -fsSL "https://repo1.maven.org/maven2/com/microsoft/playwright/driver-bundle/${PLAYWRIGHT_VERSION}/driver-bundle-${PLAYWRIGHT_VERSION}.jar" -o driver-bundle.jar \
    && unzip -q driver-bundle.jar "driver/linux$([ "$(uname -m)" = "aarch64" ] || [ "$(uname -m)" = "arm64" ] && echo '-arm64')/*" -d /tmp/pw \
    && mkdir -p ${PLAYWRIGHT_CLI_DIR} \
    && mv /tmp/pw/driver/linux*/* ${PLAYWRIGHT_CLI_DIR}/ \
    && ${PLAYWRIGHT_CLI_DIR}/node ${PLAYWRIGHT_CLI_DIR}/package/cli.js install chromium --only-shell --with-deps  \
    && apt-get purge -y --auto-remove curl unzip \
    && rm -rf /var/lib/apt/lists/* /var/cache/apt/* cp.txt playwright.jar driver.jar driver-bundle.jar /tmp/pw
########## SETUP PLAYWRIGHT DEPENDENCIES END ##########

# Validate
RUN /app.native '<title>aa</title><div style="color:black;"><img>'

ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
ENV LANGUAGE=en_US.UTF-8
EXPOSE 8080
ENTRYPOINT ["/app.native"]
